version: "3"

services:

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIME}
    volumes:
      - ./h_config:/config
    ports:
      - 8500:80
      - 4343:443
    restart: unless-stopped